import { nanoid } from "nanoid";
import { CUSTOMERS_TABLE } from "../constants/tableNames.js";

const customers = [
  {
    email: "johan.svensson@example.se",
    password: "lösenord123",
    firstname: "Johan",
    surname: "Svensson",
    address: "Storgatan 12",
    zipcode: "12345",
    city: "Stockholm",
    phoneNumber: "+46 70 123 45 67",
  },
  {
    email: "anna.johansson@example.se",
    password: "säkertLösen456",
    firstname: "Anna",
    surname: "Johansson",
    address: "Långgatan 45",
    zipcode: "54321",
    city: "Göteborg",
    phoneNumber: "+46 73 234 56 78",
  },
  {
    email: "erik.nilsson@example.se",
    password: "välkommen789",
    firstname: "Erik",
    surname: "Nilsson",
    address: "Kyrkogatan 7",
    zipcode: "11223",
    city: "Malmö",
    phoneNumber: "+46 72 345 67 89",
  },
  {
    email: "emma.olsson@example.se",
    password: "minKod123!",
    firstname: "Emma",
    surname: "Olsson",
    address: "Drottninggatan 20",
    zipcode: "22111",
    city: "Uppsala",
    phoneNumber: "+46 76 456 78 90",
  },
  {
    email: "karl.andersson@example.se",
    password: "lösen123!",
    firstname: "Karl",
    surname: "Andersson",
    address: "Kungsgatan 34",
    zipcode: "33100",
    city: "Västerås",
    phoneNumber: "+46 70 567 89 01",
  },
  {
    email: "sofie.larsson@example.se",
    password: "säkertPass!",
    firstname: "Sofie",
    surname: "Larsson",
    address: "Järnvägsgatan 56",
    zipcode: "41123",
    city: "Örebro",
    phoneNumber: "+46 73 678 90 12",
  },
  {
    email: "oscar.persson@example.se",
    password: "tryggLösen789",
    firstname: "Oscar",
    surname: "Persson",
    address: "Linnégatan 8",
    zipcode: "55112",
    city: "Linköping",
    phoneNumber: "+46 72 789 01 23",
  },
  {
    email: "lisa.eriksson@example.se",
    password: "kod12345",
    firstname: "Lisa",
    surname: "Eriksson",
    address: "Västra Allén 3",
    zipcode: "66100",
    city: "Helsingborg",
    phoneNumber: "+46 76 890 12 34",
  },
  {
    email: "anders.berg@example.se",
    password: "minLösenKod!",
    firstname: "Anders",
    surname: "Berg",
    address: "Centralgatan 19",
    zipcode: "72123",
    city: "Norrköping",
    phoneNumber: "+46 70 901 23 45",
  },
  {
    email: "klara.holm@example.se",
    password: "hejhejhej!",
    firstname: "Klara",
    surname: "Holm",
    address: "Strandvägen 10",
    zipcode: "88123",
    city: "Lund",
    phoneNumber: "+46 73 123 45 67",
  },
];
const batchWriteRequests = customers.map((customer) => ({
  PutRequest: {
    Item: {
      customerID: nanoid(),
      email: customer.email,
      password: customer.password,
      firstname: customer.firstname,
      surname: customer.surname,
      address: customer.address,
      zipcode: customer.zipcode,
      city: customer.city,
      phoneNumber: customer.phoneNumber,
      createdAt: new Date().toISOString(),
    },
  },
}));
export const customerParams = {
  RequestItems: {
    [CUSTOMERS_TABLE]: batchWriteRequests,
  },
};
