# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: dylanr96
# "service" is the name of this project. This will also be added to your AWS resource names.
service: syntax-squad

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
          Resource: "*"
functions:
  # Admin
  createAdmin:
    handler: src/handlers/adminHandler.createAdmin
    events:
      - httpApi:
          path: /admin
          method: POST
  loginAdmin:
    handler: src/handlers/adminHandler.loginAdmin
    events:
      - httpApi:
          path: /admin/login
          method: POST
  getAdmin:
    handler: src/handlers/adminHandler.getAdmin
    events:
      - httpApi:
          path: /admin/{adminID}
          method: GET
  changeEmailAdmin:
    handler: src/handlers/adminHandler.changeEmail
    events:
      - httpApi:
          path: /admin
          method: PUT
  deleteAdmin:
    handler: src/handlers/adminHandler.deleteAdmin
    events:
      - httpApi:
          path: /admin/{adminID}
          method: DELETE
  # Customers
  createCustomer:
    handler: src/handlers/customerHandler.createCustomer
    events:
      - httpApi:
          path: /customer
          method: POST
  loginCustomer:
    handler: src/handlers/customerHandler.loginCustomer
    events:
      - httpApi:
          path: /customer/login
          method: POST
  getCustomers:
    handler: src/handlers/customerHandler.getCustomers
    events:
      - httpApi:
          path: /customers
          method: GET
  getCustomer:
    handler: src/handlers/customerHandler.getCustomer
    events:
      - httpApi:
          path: /customer/{customerID}
          method: GET
  editCustomer:
    handler: src/handlers/customerHandler.editCustomer
    events:
      - httpApi:
          path: /customer
          method: PUT
  deleteCustomer:
    handler: src/handlers/customerHandler.deleteCustomer
    events:
      - httpApi:
          path: /customer/{customerID}
          method: DELETE
  # Ingredients
  addIngredient:
    handler: src/handlers/ingredientHandler.addIngredient
    events:
      - httpApi:
          path: /ingredient
          method: POST
  deleteIngredient:
    handler: src/handlers/ingredientHandler.deleteIngredient
    events:
      - httpApi:
          path: /ingredient
          method: DELETE
  editIngredient:
    handler: src/handlers/ingredientHandler.editIngredient
    events:
      - httpApi:
          path: /ingredient
          method: PUT
  getIngredientsById:
    handler: src/handlers/ingredientHandler.getIngredientsByIds
    events:
      - httpApi:
          path: /ingredientsById
          method: POST
  getAllIngredients:
    handler: src/handlers/ingredientHandler.getAllIngredients
    events:
      - httpApi:
          path: /ingredients
          method: GET
  # Products
  getAllProducts:
    handler: src/handlers/productHandler.getAllProducts
    events:
      - httpApi:
          path: /products
          method: GET
  getProduct:
    handler: src/handlers/productHandler.getProduct
    events:
      - httpApi:
          path: /product/{productID}
          method: GET
  createProduct:
    handler: src/handlers/productHandler.createProduct
    events:
      - httpApi:
          path: /product
          method: POST
  editProduct:
    handler: src/handlers/productHandler.editProduct
    events:
      - httpApi:
          path: /product
          method: PUT
  deleteProduct:
    handler: src/handlers/productHandler.deleteProduct
    events:
      - httpApi:
          path: /product/{productID}
          method: DELETE
  # Orders
  createOrder:
    handler: src/handlers/orderHandler.createOrder
    events:
      - httpApi:
          path: /order
          method: POST
  changeOrder:
    handler: src/handlers/orderHandler.changeOrder
    events:
      - httpApi:
          path: /order
          method: PUT
  deleteOrder:
    handler: src/handlers/orderHandler.deleteOrder
    events:
      - httpApi:
          path: /order/{orderNO}
          method: DELETE
  changeOrderStatus:
    handler: src/handlers/orderHandler.changeOrderStatus
    events:
      - httpApi:
          path: /orderStatus
          method: PUT
  getOrderByUserID:
    handler: src/handlers/orderHandler.getOrderByUserID
    events:
      - httpApi:
          path: /myOrders
          method: GET
  getOrder:
    handler: src/handlers/orderHandler.getOrder
    events:
      - httpApi:
          path: /order/{orderNO}
          method: GET
  getAllOrders:
    handler: src/handlers/orderHandler.getAllOrders
    events:
      - httpApi:
          path: /orders
          method: GET
resources:
  Resources:
    AdminTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: easybake_admins
        AttributeDefinitions:
          - AttributeName: adminID
            AttributeType: S
        KeySchema:
          - AttributeName: adminID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: easybake_customers
        AttributeDefinitions:
          - AttributeName: customerID
            AttributeType: S
        KeySchema:
          - AttributeName: customerID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    InfoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: easybake_info
        AttributeDefinitions:
          - AttributeName: shopID
            AttributeType: S
        KeySchema:
          - AttributeName: shopID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: easybake_products
        AttributeDefinitions:
          - AttributeName: productID
            AttributeType: N
        KeySchema:
          - AttributeName: productID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    IngredientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: easybake_ingredients
        AttributeDefinitions:
          - AttributeName: ingredientID
            AttributeType: N
        KeySchema:
          - AttributeName: ingredientID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: easybake_orders
        AttributeDefinitions:
          - AttributeName: orderNO
            AttributeType: N
          - AttributeName: userID
            AttributeType: S
        KeySchema:
          - AttributeName: orderNO
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIDIndex
            KeySchema:
              - AttributeName: userID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST